import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,CalendarDays,Clock,MapPin,Users} from "lucide-react";
import {Footer,Header} from "@/app/site-components";
import {EventRegistration} from "@/app/public-forms";
import {safeQuery} from "@/lib/db";

type EventItem={id:string;kind:"course"|"event";slug:string;title:string;excerpt:string|null;description:{body?:string[];note?:string}|string;cover_image_url:string|null;starts_at:string;ends_at:string|null;venue:string|null;address:string|null;capacity:number|null;registration_enabled:boolean};
async function getEvent(slug:string){return (await safeQuery<EventItem>("SELECT id,kind,slug,title,excerpt,description,cover_image_url,starts_at,ends_at,venue,address,capacity,registration_enabled FROM events WHERE status='published' AND slug=$1 LIMIT 1",[slug]).catch(()=>[]))[0]}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=await getEvent((await params).slug);return item?{title:`${item.title} | ACI Sindilojas`,description:item.excerpt}:{title:"Evento não encontrado | ACI Sindilojas"}}

export default async function EventPage({params}:{params:Promise<{slug:string}>}){const item=await getEvent((await params).slug);if(!item)notFound();const description=typeof item.description==="string"?JSON.parse(item.description):item.description;const paragraphs:string[]=Array.isArray(description?.body)&&description.body.length?description.body:item.excerpt?[item.excerpt]:[];const start=new Date(item.starts_at);return <><Header/><main><article className="event-detail"><header><div className="container"><Link href="/cursos-e-eventos" className="news-back"><ArrowLeft size={16}/> Voltar para agenda</Link><span className="eyebrow light">{item.kind==="course"?"Curso":"Evento"}</span><h1>{item.title}</h1><p>{item.excerpt}</p></div></header><div className="container event-detail-grid"><section>{item.cover_image_url&&<img className="event-cover" src={item.cover_image_url} alt=""/>}<div className="prose">{paragraphs.map((paragraph:string,index:number)=><p key={`${index}-${paragraph}`}>{paragraph}</p>)}{description?.note&&<aside>{description.note}</aside>}</div></section><aside className="event-info-card"><h2>Informações</h2><p><CalendarDays size={18}/><span><strong>{start.toLocaleDateString("pt-BR",{day:"2-digit",month:"long",year:"numeric"})}</strong>{start.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></p>{item.ends_at&&<p><Clock size={18}/><span><strong>Término</strong>{new Date(item.ends_at).toLocaleString("pt-BR")}</span></p>}{item.venue&&<p><MapPin size={18}/><span><strong>{item.venue}</strong>{item.address}</span></p>}{item.capacity&&<p><Users size={18}/><span><strong>{item.capacity} vagas</strong>Sujeito à disponibilidade</span></p>}{item.registration_enabled&&<div className="event-detail-registration"><EventRegistration eventId={item.id} title={item.title}/></div>}</aside></div></article></main><Footer/></>}
