import Link from "next/link";
import {ArrowRight,CalendarDays,Footer,Header,QuickAccess,solutionIcons,type Solution} from "./site-components";
import {HistoryVideoDialog} from "./video-dialog";
import {HeroCarousel} from "./hero-carousel";
import {safeQuery} from "@/lib/db";
import {getSettingGroup,getSettingObject} from "@/lib/site-data";

type Banner={id:string;title:string|null;subtitle:string|null;desktop_image_url:string;mobile_image_url:string|null;image_alt:string;primary_button_label:string|null;primary_button_url:string|null;secondary_button_label:string|null;secondary_button_url:string|null;image_only:boolean};
type News={id:string;slug:string;title:string;excerpt:string|null;published_at:string;cover_image_url:string|null;content:unknown};
type Event={id:string;kind:string;title:string;excerpt:string|null;starts_at:string;venue:string|null;registration_enabled:boolean};

export const dynamic="force-dynamic";
const homeFallback={about_eyebrow:"Quem somos",about_title:"A soma da força de todos é sempre maior.",about_text:"Somos a união de empreendedores que somam forças para fortalecer negócios, representar interesses e criar oportunidades para Três de Maio e região.",about_year_aci:"1979",about_year_sindilojas:"2002",services_eyebrow:"Soluções para associados",services_title:"Mais estrutura para o seu negócio crescer.",services_text:"Serviços práticos, orientação e vantagens pensadas para o dia a dia das empresas.",cta_eyebrow:"Faça parte",cta_title:"Seu negócio não precisa crescer sozinho.",cta_text:"Conecte-se a uma rede que representa, apoia e abre caminhos para quem empreende.",location_eyebrow:"Onde estamos",location_title:"Estamos no coração de Três de Maio.",location_text:"Centro Empresarial Sicredi ACI Sindilojas",address:"Av. Uruguai, 366 — 2º andar, Centro.",maps_embed_url:"https://www.google.com/maps?q=Av.%20Uruguai%2C%20366%2C%20Tr%C3%AAs%20de%20Maio%2C%20RS&output=embed",route_url:"https://maps.app.goo.gl/aTWfo2fQXf5QzvPT9"};
export default async function Home(){const [banners,news,eventRows,home,solutionRows]=await Promise.all([safeQuery<Banner>("SELECT id,title,subtitle,desktop_image_url,mobile_image_url,image_alt,primary_button_label,primary_button_url,secondary_button_label,secondary_button_url,image_only FROM banners WHERE status='published' AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>=now()) ORDER BY display_order").catch(()=>[]),safeQuery<News>("SELECT id,slug,title,excerpt,published_at,cover_image_url,content FROM posts WHERE kind='news' AND status='published' ORDER BY published_at DESC NULLS LAST LIMIT 3").catch(()=>[]),safeQuery<Event>("SELECT id,kind,title,excerpt,starts_at,venue,registration_enabled FROM events WHERE status='published' AND starts_at>=now() ORDER BY starts_at LIMIT 1").catch(()=>[]),getSettingObject("home",homeFallback),getSettingGroup<Solution>("solutions")]);const nextEvent=eventRows[0];const services=solutionRows.filter(item=>item.status==="published").sort((a,b)=>Number(a.display_order||0)-Number(b.display_order||0));return <><Header/><main>
  <HeroCarousel banners={banners}/>
  <QuickAccess/>
  <section className="section about-home"><div className="container two-columns"><HistoryVideoDialog/><div className="content-block"><span className="eyebrow">{home.about_eyebrow}</span><h2>{home.about_title}</h2><p>{home.about_text}</p><div className="mini-values"><span><strong>{home.about_year_aci}</strong> Fundação da ACI</span><span><strong>{home.about_year_sindilojas}</strong> Fundação do Sindilojas</span></div><Link className="text-link" href="/sobre">Conheça a entidade <ArrowRight size={16}/></Link></div></div></section>
  <section className="section services-section"><div className="container"><div className="section-heading split-heading"><div><span className="eyebrow light">{home.services_eyebrow}</span><h2>{home.services_title}</h2></div><p>{home.services_text}</p></div><div className="service-grid">{services.map((service,index)=>{const Icon=solutionIcons[service.icon]||solutionIcons.shield;return <article className="service-card" key={service.key}><span className="service-number">{String(index+1).padStart(2,"0")}</span><Icon size={28}/><h3>{service.title}</h3><p>{service.description}</p><Link href="/solucoes" aria-label={`Saiba mais sobre ${service.title}`}><ArrowRight size={18}/></Link></article>})}</div></div></section>
  <section className="section updates-section"><div className="container updates-grid"><div><div className="section-heading inline-heading"><div><span className="eyebrow">Atualidades</span><h2>Notícias</h2></div><Link href="/noticias">Ver todas <ArrowRight size={16}/></Link></div><div className="news-list">{news.slice(0,3).map(item=><article key={item.slug}><time>{new Date(item.published_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).toUpperCase()}</time><h3>{item.title}</h3><Link href={`/noticias/${item.slug}`} aria-label={`Ler ${item.title}`}><ArrowRight size={17}/></Link></article>)}</div></div><aside className="event-card"><span className="event-icon"><CalendarDays size={25}/></span><span className="eyebrow light">Agenda</span><h2>{nextEvent?.title||"Confira nossa agenda"}</h2><p>{nextEvent?.excerpt||"Novos cursos e eventos serão publicados em breve."}</p><Link className="button button-white" href="/cursos-e-eventos">Ver calendário <ArrowRight size={17}/></Link></aside></div></section>
  <section className="cta-band"><div className="container cta-band-inner"><div><span className="eyebrow light">{home.cta_eyebrow}</span><h2>{home.cta_title}</h2></div><p>{home.cta_text}</p><Link className="button button-yellow" href="/associe">Seja um associado <ArrowRight size={18}/></Link></div></section>
  <section className="section location-section"><div className="container location-grid"><div className="map-panel"><iframe src={home.maps_embed_url} title="Mapa da ACI Sindilojas em Três de Maio" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><div className="content-block location-content"><span className="eyebrow">{home.location_eyebrow}</span><h2>{home.location_title}</h2><p>{home.location_text}<br/>{home.address}</p><a className="button button-blue" href={home.route_url} target="_blank" rel="noreferrer">Traçar rota <ArrowRight size={17}/></a></div></div></section>
  </main><Footer/></>}
