import Link from "next/link";
import {ArrowRight,CalendarDays,Footer,Header,MapPin,QuickAccess,services} from "./site-components";
import {HistoryVideoDialog} from "./video-dialog";
import {HeroCarousel} from "./hero-carousel";
import {safeQuery} from "@/lib/db";
import {demoBanners,demoEvents,demoNews} from "@/lib/demo-content";

export const dynamic="force-dynamic";
export default async function Home(){const dbBanners=await safeQuery<typeof demoBanners[number]>("SELECT id,title,subtitle,desktop_image_url,mobile_image_url,image_alt,primary_button_label,primary_button_url,secondary_button_label,secondary_button_url,image_only FROM banners WHERE status='published' AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>=now()) ORDER BY display_order").catch(()=>[]);const dbNews=await safeQuery<typeof demoNews[number]>("SELECT id,slug,title,excerpt,published_at,cover_image_url,content FROM posts WHERE kind='news' AND status='published' ORDER BY published_at DESC NULLS LAST LIMIT 3").catch(()=>[]);const dbEvents=await safeQuery<typeof demoEvents[number]>("SELECT id,kind,title,excerpt,starts_at,venue,registration_enabled FROM events WHERE status='published' AND starts_at>=now() ORDER BY starts_at LIMIT 1").catch(()=>[]);const banners=dbBanners.length?dbBanners:demoBanners;const news=dbNews.length?dbNews:demoNews;const nextEvent=dbEvents[0]||demoEvents[0];return <><Header/><main>
  <HeroCarousel banners={banners}/>
  <QuickAccess/>
  <section className="section about-home"><div className="container two-columns"><HistoryVideoDialog/><div className="content-block"><span className="eyebrow">Quem somos</span><h2>A soma da força de todos é sempre maior.</h2><p>Somos a união de empreendedores que somam forças para fortalecer negócios, representar interesses e criar oportunidades para Três de Maio e região.</p><div className="mini-values"><span><strong>1979</strong> Fundação da ACI</span><span><strong>2002</strong> Fundação do Sindilojas</span></div><Link className="text-link" href="/sobre">Conheça a entidade <ArrowRight size={16}/></Link></div></div></section>
  <section className="section services-section"><div className="container"><div className="section-heading split-heading"><div><span className="eyebrow light">Soluções para associados</span><h2>Mais estrutura para o seu negócio crescer.</h2></div><p>Serviços práticos, orientação e vantagens pensadas para o dia a dia das empresas.</p></div><div className="service-grid">{services.map(({title,description,icon:Icon},index)=><article className="service-card" key={title}><span className="service-number">0{index+1}</span><Icon size={28}/><h3>{title}</h3><p>{description}</p><Link href="/solucoes" aria-label={`Saiba mais sobre ${title}`}><ArrowRight size={18}/></Link></article>)}</div></div></section>
  <section className="section updates-section"><div className="container updates-grid"><div><div className="section-heading inline-heading"><div><span className="eyebrow">Atualidades</span><h2>Notícias</h2></div><Link href="/noticias">Ver todas <ArrowRight size={16}/></Link></div><div className="news-list">{news.slice(0,3).map(item=><article key={item.slug}><time>{new Date(item.published_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).toUpperCase()}</time><h3>{item.title}</h3><Link href={`/noticias/${item.slug}`} aria-label={`Ler ${item.title}`}><ArrowRight size={17}/></Link></article>)}</div></div><aside className="event-card"><span className="event-icon"><CalendarDays size={25}/></span><span className="eyebrow light">Agenda</span><h2>{nextEvent.title}</h2><p>{nextEvent.excerpt}</p><Link className="button button-white" href="/cursos-e-eventos">Ver calendário <ArrowRight size={17}/></Link></aside></div></section>
  <section className="cta-band"><div className="container cta-band-inner"><div><span className="eyebrow light">Faça parte</span><h2>Seu negócio não precisa crescer sozinho.</h2></div><p>Conecte-se a uma rede que representa, apoia e abre caminhos para quem empreende.</p><Link className="button button-yellow" href="/associe">Seja um associado <ArrowRight size={18}/></Link></div></section>
  <section className="section location-section"><div className="container location-grid"><div className="map-panel"><span className="map-pin"><MapPin size={24}/></span><div className="map-lines"/></div><div className="content-block"><span className="eyebrow">Onde estamos</span><h2>Estamos no coração de Três de Maio.</h2><p>Centro Empresarial Sicredi ACI Sindilojas<br/>Av. Uruguai, 366 — 2º andar, Centro.</p><a className="button button-blue" href="https://maps.app.goo.gl/aTWfo2fQXf5QzvPT9">Traçar rota <ArrowRight size={17}/></a></div></div></section>
  </main><Footer/></>}
