"use client";

import {FormEvent,useState} from "react";
import {ArrowRight} from "lucide-react";

function useSubmit(endpoint:string){const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>,extra:Record<string,string>={}){event.preventDefault();setBusy(true);setStatus("");const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,...extra})});setBusy(false);if(response.ok){setStatus("Recebemos seus dados. Nossa equipe entrará em contato.");event.currentTarget.reset()}else{const result=await response.json();setStatus(result.error||"Não foi possível enviar. Tente novamente.")}}return{submit,status,busy}}

export function ContactForm(){const{submit,status,busy}=useSubmit("/api/forms");return <form className="contact-form" onSubmit={e=>submit(e,{form_type:"contact"})}><label>Nome<input name="name" required placeholder="Como podemos chamar você?"/></label><label>E-mail<input type="email" name="email" required placeholder="voce@empresa.com.br"/></label><label>Telefone<input name="phone" required placeholder="(55) 99999-9999"/></label><label>Assunto<input name="subject" required placeholder="Sobre o que deseja falar?"/></label><label className="full">Mensagem<textarea name="message" required rows={5} placeholder="Conte como podemos ajudar"/></label>{status&&<p className="form-message full">{status}</p>}<button className="button button-blue" disabled={busy}>{busy?"Enviando…":"Enviar mensagem"} <ArrowRight size={17}/></button></form>}

export function MembershipForm(){const{submit,status,busy}=useSubmit("/api/forms");return <form className="membership-form" onSubmit={e=>submit(e,{form_type:"membership"})}><label>Nome completo<input name="name" required/></label><label>E-mail<input type="email" name="email" required/></label><label>Telefone / WhatsApp<input name="phone" required/></label><label>Empresa<input name="company" required/></label><label>CNPJ<input name="cnpj"/></label><label>Segmento<input name="segment"/></label><label className="wide">Conte um pouco sobre a empresa<textarea name="message" rows={4}/></label>{status&&<p className="form-message wide">{status}</p>}<button className="button button-yellow" disabled={busy}>{busy?"Enviando…":"Quero ser associado"} <ArrowRight size={17}/></button></form>}

export function EventRegistration({eventId,title}:{eventId:string;title:string}){const{submit,status,busy}=useSubmit("/api/registrations");return <form className="event-registration" onSubmit={e=>submit(e,{event_id:eventId})}><h3>Inscrição — {title}</h3><label>Nome<input name="name" required/></label><label>E-mail<input type="email" name="email" required/></label><label>WhatsApp<input name="phone" required/></label><label>Empresa<input name="company"/></label>{status&&<p className="form-message">{status}</p>}<button className="button button-blue" disabled={busy}>{busy?"Enviando…":"Confirmar inscrição"}</button></form>}
