import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Building2, CalendarDays, ChevronRight, Handshake, Landmark, MapPin, Menu, MessageCircle, Phone, Play, ShieldCheck, Smartphone, Users } from "lucide-react";

export const mainNav = [["Início","/"],["Sobre","/sobre"],["Soluções","/solucoes"],["Notícias","/noticias"],["Vídeos","/videos-lives"],["Contato","/contato"]] as const;
export const quickNav = [["Vagas","/vagas",BriefcaseBusiness],["Cursos e eventos","/cursos-e-eventos",CalendarDays],["Parceiros e convênios","/convenios",Handshake],["Associados","/associados",Users],["Legislação","/legislacao",Landmark]] as const;
export const services = [
  {title:"Certificado Digital",description:"Emissão de e-CPF e e-CNPJ com orientação e atendimento próximo.",icon:ShieldCheck},
  {title:"SCPC",description:"Consultas de proteção ao crédito para pessoas físicas e jurídicas.",icon:Landmark},
  {title:"Espaços para eventos",description:"Cinco ambientes preparados para reuniões, cursos e encontros empresariais.",icon:Building2},
  {title:"Telefonia móvel",description:"Planos corporativos com condições especiais para associados.",icon:Smartphone},
  {title:"Eventos empresariais",description:"Apoio para palestras, cafés, reuniões, seminários e ações em parceria.",icon:CalendarDays},
] as const;

export function Header(){return <header className="site-header"><div className="quick-bar"><div className="container quick-bar-inner"><span>Conexões que fortalecem negócios</span><nav aria-label="Acessos rápidos">{quickNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav></div></div><div className="container main-header"><Link href="/" className="brand" aria-label="ACI Sindilojas — início"><img src="/brand/logo.png" alt="ACI e Sindilojas Três de Maio"/></Link><nav className="desktop-nav" aria-label="Navegação principal">{mainNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><Link className="button button-outline desktop-join" href="/associe">Seja um associado <ArrowRight size={17}/></Link><details className="mobile-menu"><summary aria-label="Abrir menu"><Menu size={24}/></summary><nav>{mainNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}{quickNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link href="/associe">Seja um associado</Link></nav></details></div></header>}

function BrandIcon({name}:{name:"instagram"|"facebook"|"youtube"|"whatsapp"}){
  if(name==="instagram")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.5" cy="6.5" r="1" className="brand-dot"/></svg>;
  if(name==="facebook")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.2 8.2V6.7c0-.7.5-.9 1-.9h2.4V2.2L14.3 2c-3.2 0-5.1 1.9-5.1 5.3v.9H6v4h3.2V22h4.6v-9.8h3.4l.6-4h-4Z"/></svg>;
  if(name==="youtube")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 7.1a2.8 2.8 0 0 0-2-2C17.8 4.6 12 4.6 12 4.6s-5.8 0-7.6.5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2 12a29 29 0 0 0 .4 4.9 2.8 2.8 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.8 2.8 0 0 0 2-2A29 29 0 0 0 22 12a29 29 0 0 0-.4-4.9Z"/><path className="brand-cut" d="m10 15.5 5-3.5-5-3.5Z"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .3 5.3.3 11.8c0 2.1.6 4.2 1.6 6L.2 24l6.4-1.7c1.7.9 3.6 1.4 5.5 1.4 6.5 0 11.8-5.3 11.8-11.8 0-3.2-1.2-6.1-3.4-8.4Zm-8.4 18.2c-1.8 0-3.5-.5-5-1.4l-.4-.2-3.8 1 1-3.7-.2-.4a9.8 9.8 0 1 1 8.4 4.7Zm5.4-7.4c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1-1.8-.9-3-1.7-4.2-3.8-.3-.5.3-.5.9-1.7.1-.2 0-.5 0-.7l-1-2.4c-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.7.1-1 .5-.3.4-1.3 1.3-1.3 3.1 0 1.9 1.4 3.7 1.5 3.9.2.2 2.7 4.1 6.5 5.7 2.4 1 3.4 1.1 4.7.9.8-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg>;
}

const contactChannels=[
  {title:"Atendimento",display:<><span>(55) 9 9995-4200</span><span>(55) 3535-1338</span></>,whatsapp:"https://wa.me/5555999954200",phone:"tel:+555535351338"},
  {title:"Financeiro",display:<span>(55) 9 9619-3291</span>,whatsapp:"https://wa.me/5555996193291",phone:"tel:+5555996193291"},
  {title:"Marketing",display:<span>(55) 9 9696-6404</span>,whatsapp:"https://wa.me/5555996966404",phone:"tel:+5555996966404"},
  {title:"Telefonia",display:<span>(55) 9 9622-1885</span>,whatsapp:"https://wa.me/5555996221885",phone:"tel:+5555996221885"},
  {title:"Comercial e eventos",display:<span>(55) 9 9935-8073</span>,whatsapp:"https://wa.me/5555999358073",phone:"tel:+5555999358073"},
];

export function ContactChannels(){return <section className="contact-channels" aria-labelledby="contact-channels-title"><div className="container"><div className="contact-channels-heading"><span className="eyebrow">Contato</span><h2 id="contact-channels-title">Fale direto com o setor que você precisa.</h2></div><div className="contact-channel-grid">{contactChannels.map(channel=><article key={channel.title}><h3>{channel.title}</h3><p>{channel.display}</p><div><a href={channel.whatsapp} target="_blank" rel="noreferrer" aria-label={`WhatsApp ${channel.title}`}><BrandIcon name="whatsapp"/></a><a href={channel.phone} aria-label={`Ligar para ${channel.title}`}><Phone size={19}/></a></div></article>)}</div></div></section>}

export function Footer(){return <><ContactChannels/><footer className="footer"><div className="container footer-grid"><div className="footer-brand"><img src="/brand/logo.png" alt="ACI Sindilojas Três de Maio"/><p>A força de quem empreende, conectada para transformar Três de Maio e região.</p><div className="socials"><a aria-label="Instagram da ACI Sindilojas" href="https://www.instagram.com/acisindilojastm/" target="_blank" rel="noreferrer"><BrandIcon name="instagram"/></a><a aria-label="Facebook da ACI Sindilojas" href="https://www.facebook.com/acisindilojastm/" target="_blank" rel="noreferrer"><BrandIcon name="facebook"/></a><a aria-label="YouTube da ACI Sindilojas" href="https://www.youtube.com/@acisindilojastm" target="_blank" rel="noreferrer"><BrandIcon name="youtube"/></a></div></div><div><h3>Institucional</h3><Link href="/sobre">Sobre</Link><Link href="/solucoes">Soluções</Link><Link href="/noticias">Notícias</Link><Link href="/contato">Contato e ouvidoria</Link></div><div><h3>Acessos</h3><Link href="/vagas">Vagas de trabalho</Link><Link href="/cursos-e-eventos">Cursos e eventos</Link><Link href="/convenios">Parceiros e convênios</Link><Link href="/associados">Associados</Link></div><div><h3>Fale conosco</h3><a href="tel:+555535351338"><Phone size={15}/> (55) 3535-1338</a><a href="https://wa.me/5555999954200"><MessageCircle size={15}/> (55) 9 9995-4200</a><p><MapPin size={15}/> Av. Uruguai, 366 — 2º andar<br/>Centro, Três de Maio/RS</p></div></div><div className="container footer-bottom"><span>© 2026 ACI Sindilojas. Todos os direitos reservados.</span><span><Link href="/politica-de-privacidade">Privacidade</Link> · <Link href="/termos-de-uso">Termos de uso</Link></span></div></footer><a className="whatsapp-float" href="https://wa.me/5555999954200" target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp"><BrandIcon name="whatsapp"/></a></>}

export function PageHero({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="page-hero"><div className="container"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}
export function EmptyState({icon:Icon,title,text}:{icon:typeof Users;title:string;text:string}){return <div className="empty-state"><span><Icon size={26}/></span><h2>{title}</h2><p>{text}</p><Link className="text-link" href="/contato">Falar com a ACI Sindilojas <ArrowRight size={16}/></Link></div>}
export function QuickAccess(){return <section className="quick-access" aria-label="Acessos rápidos"><div className="container quick-grid">{quickNav.map(([label,href,Icon])=><Link key={href} href={href}><Icon size={22}/><span>{label}</span><ChevronRight size={18}/></Link>)}</div></section>}
export {ArrowRight,BriefcaseBusiness,CalendarDays,Handshake,Landmark,MapPin,MessageCircle,Play,Users};
