import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Building2, CalendarDays, ChevronRight, Handshake, Landmark, MapPin, Menu, MessageCircle, Phone, Play, ShieldCheck, Smartphone, Users } from "lucide-react";
import {getSettingGroup,getSettingObject} from "@/lib/site-data";

export const mainNav = [["Início","/"],["Sobre","/sobre"],["Soluções","/solucoes"],["Notícias","/noticias"],["Vídeos","/videos-lives"],["Contato","/contato"]] as const;
export const quickNav = [["Vagas","/vagas",BriefcaseBusiness],["Cursos e eventos","/cursos-e-eventos",CalendarDays],["Parceiros e convênios","/convenios",Handshake],["Associados","/associados",Users],["Legislação","/legislacao",Landmark]] as const;
export const solutionIcons={shield:ShieldCheck,landmark:Landmark,building:Building2,smartphone:Smartphone,calendar:CalendarDays};
export type Solution={key:string;title:string;description:string;icon:keyof typeof solutionIcons;cta_label?:string;cta_url?:string;display_order?:number;status?:string};
export type ContactChannel={key:string;title:string;display_phone:string;whatsapp:string;phone?:string;display_order?:number;status?:string};
export const generalFallback={contact_hero_eyebrow:"Fale conosco",contact_hero_title:"Como podemos ajudar?",contact_hero_text:"Nossa equipe está pronta para orientar você e encontrar o canal certo para cada necessidade.",footer_description:"A força de quem empreende, conectada para transformar Três de Maio e região.",address:"Av. Uruguai, 366 — 2º andar\nCentro, Três de Maio/RS",general_phone:"555535351338",general_whatsapp:"5555999954200",floating_whatsapp:"5555999954200",instagram_url:"https://www.instagram.com/acisindilojastm/",facebook_url:"https://www.facebook.com/acisindilojastm/",youtube_url:"https://www.youtube.com/@acisindilojastm",copyright_text:"© 2026 ACI Sindilojas. Todos os direitos reservados."};

export function Header(){return <header className="site-header"><div className="quick-bar"><div className="container quick-bar-inner"><span>Conexões que fortalecem negócios</span><nav aria-label="Acessos rápidos">{quickNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav></div></div><div className="container main-header"><Link href="/" className="brand" aria-label="ACI Sindilojas — início"><img src="/brand/logo.png" alt="ACI e Sindilojas Três de Maio"/></Link><nav className="desktop-nav" aria-label="Navegação principal">{mainNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><Link className="button button-outline desktop-join" href="/associe">Seja um associado <ArrowRight size={17}/></Link><details className="mobile-menu"><summary aria-label="Abrir menu"><Menu size={24}/></summary><nav>{mainNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}{quickNav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link href="/associe">Seja um associado</Link></nav></details></div></header>}

function BrandIcon({name}:{name:"instagram"|"facebook"|"youtube"|"whatsapp"}){
  if(name==="instagram")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.5" cy="6.5" r="1" className="brand-dot"/></svg>;
  if(name==="facebook")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.2 8.2V6.7c0-.7.5-.9 1-.9h2.4V2.2L14.3 2c-3.2 0-5.1 1.9-5.1 5.3v.9H6v4h3.2V22h4.6v-9.8h3.4l.6-4h-4Z"/></svg>;
  if(name==="youtube")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.6 7.1a2.8 2.8 0 0 0-2-2C17.8 4.6 12 4.6 12 4.6s-5.8 0-7.6.5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2 12a29 29 0 0 0 .4 4.9 2.8 2.8 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.8 2.8 0 0 0 2-2A29 29 0 0 0 22 12a29 29 0 0 0-.4-4.9Z"/><path className="brand-cut" d="m10 15.5 5-3.5-5-3.5Z"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .3 5.3.3 11.8c0 2.1.6 4.2 1.6 6L.2 24l6.4-1.7c1.7.9 3.6 1.4 5.5 1.4 6.5 0 11.8-5.3 11.8-11.8 0-3.2-1.2-6.1-3.4-8.4Zm-8.4 18.2c-1.8 0-3.5-.5-5-1.4l-.4-.2-3.8 1 1-3.7-.2-.4a9.8 9.8 0 1 1 8.4 4.7Zm5.4-7.4c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1-1.8-.9-3-1.7-4.2-3.8-.3-.5.3-.5.9-1.7.1-.2 0-.5 0-.7l-1-2.4c-.3-.6-.5-.5-.7-.5h-.6c-.2 0-.7.1-1 .5-.3.4-1.3 1.3-1.3 3.1 0 1.9 1.4 3.7 1.5 3.9.2.2 2.7 4.1 6.5 5.7 2.4 1 3.4 1.1 4.7.9.8-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.5-.1-.1-.3-.2-.6-.4Z"/></svg>;
}

export async function getContactChannels(){const rows=await getSettingGroup<ContactChannel>("whatsapp");return rows.filter(item=>item.status!=="draft"&&item.status!=="archived").sort((a,b)=>Number(a.display_order||0)-Number(b.display_order||0))}
export async function ContactChannels(){const contactChannels=await getContactChannels();if(!contactChannels.length)return null;return <section className="contact-channels" aria-labelledby="contact-channels-title"><div className="container"><div className="contact-channels-heading"><span className="eyebrow">Contato</span><h2 id="contact-channels-title">Fale direto com o setor que você precisa.</h2></div><div className="contact-channel-grid">{contactChannels.map(channel=><article key={channel.key}><h3>{channel.title}</h3><p>{channel.display_phone.split("\n").map(number=><span key={number}>{number}</span>)}</p><div><a href={`https://wa.me/${channel.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" aria-label={`WhatsApp ${channel.title}`}><BrandIcon name="whatsapp"/></a>{channel.phone&&<a href={`tel:+${channel.phone.replace(/\D/g,"")}`} aria-label={`Ligar para ${channel.title}`}><Phone size={19}/></a>}</div></article>)}</div></div></section>}

export async function Footer(){const general=await getSettingObject("general",generalFallback);const phone=String(general.general_phone).replace(/\D/g,"");const whatsapp=String(general.general_whatsapp).replace(/\D/g,"");const floating=String(general.floating_whatsapp||general.general_whatsapp).replace(/\D/g,"");return <><ContactChannels/><footer className="footer"><div className="container footer-grid"><div className="footer-brand"><img src="/brand/logo.png" alt="ACI Sindilojas Três de Maio"/><p>{String(general.footer_description)}</p><div className="socials"><a aria-label="Instagram da ACI Sindilojas" href={String(general.instagram_url)} target="_blank" rel="noreferrer"><BrandIcon name="instagram"/></a><a aria-label="Facebook da ACI Sindilojas" href={String(general.facebook_url)} target="_blank" rel="noreferrer"><BrandIcon name="facebook"/></a><a aria-label="YouTube da ACI Sindilojas" href={String(general.youtube_url)} target="_blank" rel="noreferrer"><BrandIcon name="youtube"/></a></div></div><div><h3>Institucional</h3><Link href="/sobre">Sobre</Link><Link href="/solucoes">Soluções</Link><Link href="/noticias">Notícias</Link><Link href="/contato">Contato e ouvidoria</Link></div><div><h3>Acessos</h3><Link href="/vagas">Vagas de trabalho</Link><Link href="/cursos-e-eventos">Cursos e eventos</Link><Link href="/convenios">Parceiros e convênios</Link><Link href="/associados">Associados</Link></div><div><h3>Fale conosco</h3><a href={`tel:+${phone}`}><Phone size={15}/> {String(general.general_phone)}</a><a href={`https://wa.me/${whatsapp}`}><MessageCircle size={15}/> {String(general.general_whatsapp)}</a><p><MapPin size={15}/> {String(general.address).split("\n").map((line,index)=><span key={line}>{index>0&&<br/>}{line}</span>)}</p></div></div><div className="container footer-bottom"><span>{String(general.copyright_text)}</span><span><Link href="/politica-de-privacidade">Privacidade</Link> · <Link href="/termos-de-uso">Termos de uso</Link></span></div></footer><a className="whatsapp-float" href={`https://wa.me/${floating}`} target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp"><BrandIcon name="whatsapp"/></a></>}

export function PageHero({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="page-hero"><div className="container"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section>}
export function EmptyState({icon:Icon,title,text}:{icon:typeof Users;title:string;text:string}){return <div className="empty-state"><span><Icon size={26}/></span><h2>{title}</h2><p>{text}</p><Link className="text-link" href="/contato">Falar com a ACI Sindilojas <ArrowRight size={16}/></Link></div>}
export function QuickAccess(){return <section className="quick-access" aria-label="Acessos rápidos"><div className="container quick-grid">{quickNav.map(([label,href,Icon])=><Link key={href} href={href}><Icon size={22}/><span>{label}</span><ChevronRight size={18}/></Link>)}</div></section>}
export {ArrowRight,BriefcaseBusiness,CalendarDays,Handshake,Landmark,MapPin,MessageCircle,Play,Users};
