export type Field={name:string;label:string;type?:"text"|"textarea"|"richtext"|"url"|"email"|"number"|"datetime-local"|"checkbox"|"select"|"json"|"file";required?:boolean;options?:string[];help?:string};
export type Resource={title:string;singular:string;table:string;fields:Field[];filter?:{column:string;value:string};readOnly?:boolean;primaryKey?:string;allowCreate?:boolean;deletable?:boolean;settingsObject?:boolean;settingsGroup?:string;settingsKey?:string;autoKeyFrom?:string};

const status:Field={name:"status",label:"Status",type:"select",options:["draft","published","archived"],required:true};
export const resources:Record<string,Resource>={
  banners:{title:"Banners do topo",singular:"banner",table:"banners",fields:[{name:"title",label:"Título"},{name:"subtitle",label:"Texto de apoio",type:"textarea"},{name:"desktop_image_url",label:"Imagem desktop",type:"file",required:true},{name:"mobile_image_url",label:"Imagem mobile",type:"file",help:"Recomendada para banners somente com imagem"},{name:"image_alt",label:"Texto alternativo"},{name:"primary_button_label",label:"Texto do botão"},{name:"primary_button_url",label:"Link do botão"},{name:"image_only",label:"Usar somente imagem",type:"checkbox"},{name:"display_order",label:"Ordem",type:"number"},status]},
  home:{title:"Página inicial",singular:"conteúdo da página inicial",table:"site_settings",primaryKey:"key",allowCreate:false,deletable:false,settingsObject:true,settingsKey:"home",fields:[{name:"about_eyebrow",label:"Sobre — chamada superior"},{name:"about_title",label:"Sobre — título"},{name:"about_text",label:"Sobre — texto",type:"textarea"},{name:"about_year_aci",label:"Ano de fundação da ACI"},{name:"about_year_sindilojas",label:"Ano de fundação do Sindilojas"},{name:"services_eyebrow",label:"Soluções — chamada superior"},{name:"services_title",label:"Soluções — título"},{name:"services_text",label:"Soluções — texto",type:"textarea"},{name:"cta_eyebrow",label:"Associação — chamada superior"},{name:"cta_title",label:"Associação — título"},{name:"cta_text",label:"Associação — texto",type:"textarea"},{name:"location_eyebrow",label:"Localização — chamada superior"},{name:"location_title",label:"Localização — título"},{name:"location_text",label:"Localização — nome do local",type:"textarea"},{name:"address",label:"Endereço",type:"textarea"},{name:"maps_embed_url",label:"Link do mapa incorporado",type:"url",help:"Use um endereço do Google Maps com output=embed."},{name:"route_url",label:"Link do botão Traçar rota",type:"url"}]},
  sobre:{title:"Página Sobre",singular:"conteúdo da página Sobre",table:"site_settings",primaryKey:"key",allowCreate:false,deletable:false,settingsObject:true,settingsKey:"about",fields:[{name:"hero_eyebrow",label:"Topo — chamada superior"},{name:"hero_title",label:"Topo — título"},{name:"hero_text",label:"Topo — texto",type:"textarea"},{name:"history_eyebrow",label:"História — chamada superior"},{name:"history_title",label:"História — título"},{name:"history_paragraph_1",label:"História — primeiro parágrafo",type:"textarea"},{name:"history_paragraph_2",label:"História — segundo parágrafo",type:"textarea"},{name:"mission",label:"Missão",type:"textarea"},{name:"vision",label:"Visão",type:"textarea"},{name:"aci_president",label:"Presidente da ACI"},{name:"sindilojas_president",label:"Presidente do Sindilojas"}]},
  solucoes:{title:"Soluções",singular:"solução",table:"site_settings",primaryKey:"key",settingsObject:true,settingsGroup:"solutions",autoKeyFrom:"title",fields:[{name:"title",label:"Nome da solução",required:true},{name:"description",label:"Descrição",type:"textarea",required:true},{name:"icon",label:"Ícone",type:"select",options:["shield","landmark","building","smartphone","calendar"]},{name:"cta_label",label:"Texto do botão"},{name:"cta_url",label:"Link do botão",type:"url"},{name:"display_order",label:"Ordem",type:"number"},status]},
  contato_rodape:{title:"Contato e rodapé",singular:"configuração de contato e rodapé",table:"site_settings",primaryKey:"key",allowCreate:false,deletable:false,settingsObject:true,settingsKey:"general",fields:[{name:"contact_hero_eyebrow",label:"Página de contato — chamada superior"},{name:"contact_hero_title",label:"Página de contato — título"},{name:"contact_hero_text",label:"Página de contato — texto",type:"textarea"},{name:"footer_description",label:"Texto institucional do rodapé",type:"textarea"},{name:"address",label:"Endereço exibido",type:"textarea"},{name:"general_phone",label:"Telefone geral"},{name:"general_whatsapp",label:"WhatsApp geral"},{name:"floating_whatsapp",label:"WhatsApp do botão flutuante",help:"Digite apenas números, com DDI e DDD."},{name:"instagram_url",label:"Instagram",type:"url"},{name:"facebook_url",label:"Facebook",type:"url"},{name:"youtube_url",label:"YouTube",type:"url"},{name:"copyright_text",label:"Texto de direitos autorais"}]},
  whatsapps:{title:"WhatsApps do rodapé",singular:"canal de WhatsApp",table:"site_settings",primaryKey:"key",settingsObject:true,settingsGroup:"whatsapp",autoKeyFrom:"title",fields:[{name:"title",label:"Setor",required:true},{name:"display_phone",label:"Número exibido",required:true},{name:"whatsapp",label:"WhatsApp",required:true,help:"Digite apenas números, com DDI e DDD."},{name:"phone",label:"Telefone para ligação",help:"Digite apenas números, com DDI e DDD."},{name:"display_order",label:"Ordem",type:"number"},status]},
  noticias:{title:"Notícias",singular:"notícia",table:"posts",filter:{column:"kind",value:"news"},fields:[{name:"slug",label:"Endereço",required:true},{name:"title",label:"Título",required:true},{name:"excerpt",label:"Resumo",type:"textarea"},{name:"content",label:"Corpo da notícia",type:"richtext",required:true,help:"Separe os parágrafos com uma linha em branco."},{name:"cover_image_url",label:"Imagem de capa",type:"url"},{name:"featured",label:"Destacar",type:"checkbox"},{name:"published_at",label:"Data de publicação",type:"datetime-local"},status]},
  videos:{title:"Vídeos",singular:"vídeo",table:"posts",filter:{column:"kind",value:"video"},fields:[{name:"slug",label:"Endereço",required:true},{name:"title",label:"Título",required:true},{name:"excerpt",label:"Resumo",type:"textarea"},{name:"video_url",label:"Link do YouTube",type:"url",required:true},{name:"cover_image_url",label:"Imagem de capa",type:"url"},{name:"featured",label:"Destacar",type:"checkbox"},{name:"published_at",label:"Data de publicação",type:"datetime-local"},status]},
  agenda:{title:"Cursos e eventos",singular:"item da agenda",table:"events",fields:[{name:"kind",label:"Tipo",type:"select",options:["course","event"],required:true},{name:"slug",label:"Endereço",required:true},{name:"title",label:"Título",required:true},{name:"excerpt",label:"Resumo",type:"textarea"},{name:"description",label:"Informações completas",type:"richtext",required:true,help:"Apresente programação, público, objetivos e demais informações em parágrafos."},{name:"cover_image_url",label:"Imagem de capa",type:"url"},{name:"starts_at",label:"Início",type:"datetime-local",required:true},{name:"ends_at",label:"Término",type:"datetime-local"},{name:"venue",label:"Local"},{name:"address",label:"Endereço"},{name:"capacity",label:"Vagas",type:"number"},{name:"registration_enabled",label:"Aceitar inscrições",type:"checkbox"},status]},
  parceiros:{title:"Parceiros e convênios",singular:"parceiro",table:"organizations",filter:{column:"kind",value:"partner"},fields:[{name:"name",label:"Nome",required:true},{name:"slug",label:"Endereço",required:true},{name:"logo_url",label:"Logo",type:"url"},{name:"contact_name",label:"Contato"},{name:"email",label:"E-mail",type:"email"},{name:"phone",label:"Telefone"},{name:"whatsapp",label:"WhatsApp"},{name:"website_url",label:"Site",type:"url"},{name:"presentation",label:"Apresentação",type:"textarea"},{name:"display_order",label:"Ordem",type:"number"},status]},
  associados:{title:"Associados",singular:"associado",table:"organizations",filter:{column:"kind",value:"associate"},fields:[{name:"name",label:"Nome",required:true},{name:"slug",label:"Endereço",required:true},{name:"segment",label:"Segmento"},{name:"logo_url",label:"Logo",type:"url"},{name:"email",label:"E-mail",type:"email"},{name:"phone",label:"Telefone"},{name:"whatsapp",label:"WhatsApp"},{name:"website_url",label:"Site",type:"url"},{name:"presentation",label:"Apresentação",type:"textarea"},{name:"display_order",label:"Ordem",type:"number"},status]},
  legislacao:{title:"Legislação e documentos",singular:"documento",table:"documents",fields:[{name:"title",label:"Título",required:true},{name:"slug",label:"Endereço",required:true},{name:"description",label:"Descrição",type:"textarea"},{name:"file_url",label:"Arquivo",type:"file",required:true},{name:"file_name",label:"Nome do arquivo"},{name:"category",label:"Categoria"},{name:"published_at",label:"Data de publicação",type:"datetime-local"},status]},
  vagas:{title:"Vagas",singular:"vaga",table:"jobs",fields:[{name:"title",label:"Cargo",required:true},{name:"slug",label:"Endereço",required:true},{name:"company",label:"Empresa"},{name:"location",label:"Local"},{name:"work_mode",label:"Modelo de trabalho"},{name:"employment_type",label:"Tipo de contratação"},{name:"description",label:"Descrição",type:"json"},{name:"application_url",label:"Link para candidatura",type:"url"},{name:"application_email",label:"E-mail para candidatura",type:"email"},{name:"expires_at",label:"Expira em",type:"datetime-local"},status]},
  inscricoes:{title:"Inscrições recebidas",singular:"inscrição",table:"event_registrations",readOnly:true,fields:[]},
  formularios:{title:"Formulários recebidos",singular:"formulário",table:"form_submissions",readOnly:true,fields:[]},
};

export const adminNav=["home","sobre","banners","solucoes","noticias","videos","agenda","parceiros","associados","legislacao","vagas","contato_rodape","whatsapps","inscricoes","formularios"];
