export type Field={name:string;label:string;type?:"text"|"textarea"|"richtext"|"url"|"email"|"number"|"datetime-local"|"checkbox"|"select"|"json"|"file";required?:boolean;options?:string[];help?:string};
export type Resource={title:string;singular:string;table:string;fields:Field[];filter?:{column:string;value:string};readOnly?:boolean};

const status:Field={name:"status",label:"Status",type:"select",options:["draft","published","archived"],required:true};
export const resources:Record<string,Resource>={
  banners:{title:"Banners do topo",singular:"banner",table:"banners",fields:[{name:"title",label:"Título"},{name:"subtitle",label:"Texto de apoio",type:"textarea"},{name:"desktop_image_url",label:"Imagem desktop",type:"file",required:true},{name:"mobile_image_url",label:"Imagem mobile",type:"file",help:"Recomendada para banners somente com imagem"},{name:"image_alt",label:"Texto alternativo"},{name:"primary_button_label",label:"Texto do botão"},{name:"primary_button_url",label:"Link do botão"},{name:"image_only",label:"Usar somente imagem",type:"checkbox"},{name:"display_order",label:"Ordem",type:"number"},status]},
  paginas:{title:"Páginas institucionais",singular:"página",table:"pages",fields:[{name:"slug",label:"Endereço da página",required:true},{name:"title",label:"Título",required:true},{name:"eyebrow",label:"Chamada superior"},{name:"summary",label:"Resumo",type:"textarea"},{name:"content",label:"Conteúdo",type:"json",help:"Blocos de conteúdo em JSON"},{name:"hero_image_url",label:"Imagem de destaque",type:"file"},{name:"seo_title",label:"Título para busca"},{name:"seo_description",label:"Descrição para busca",type:"textarea"},status]},
  noticias:{title:"Notícias",singular:"notícia",table:"posts",filter:{column:"kind",value:"news"},fields:[{name:"slug",label:"Endereço",required:true},{name:"title",label:"Título",required:true},{name:"excerpt",label:"Resumo",type:"textarea"},{name:"content",label:"Corpo da notícia",type:"richtext",required:true,help:"Separe os parágrafos com uma linha em branco."},{name:"cover_image_url",label:"Imagem de capa",type:"url"},{name:"featured",label:"Destacar",type:"checkbox"},{name:"published_at",label:"Data de publicação",type:"datetime-local"},status]},
  videos:{title:"Vídeos",singular:"vídeo",table:"posts",filter:{column:"kind",value:"video"},fields:[{name:"slug",label:"Endereço",required:true},{name:"title",label:"Título",required:true},{name:"excerpt",label:"Resumo",type:"textarea"},{name:"video_url",label:"Link do YouTube",type:"url",required:true},{name:"cover_image_url",label:"Imagem de capa",type:"url"},{name:"featured",label:"Destacar",type:"checkbox"},{name:"published_at",label:"Data de publicação",type:"datetime-local"},status]},
  agenda:{title:"Cursos e eventos",singular:"item da agenda",table:"events",fields:[{name:"kind",label:"Tipo",type:"select",options:["course","event"],required:true},{name:"slug",label:"Endereço",required:true},{name:"title",label:"Título",required:true},{name:"excerpt",label:"Resumo",type:"textarea"},{name:"description",label:"Informações completas",type:"richtext",required:true,help:"Apresente programação, público, objetivos e demais informações em parágrafos."},{name:"cover_image_url",label:"Imagem de capa",type:"url"},{name:"starts_at",label:"Início",type:"datetime-local",required:true},{name:"ends_at",label:"Término",type:"datetime-local"},{name:"venue",label:"Local"},{name:"address",label:"Endereço"},{name:"capacity",label:"Vagas",type:"number"},{name:"registration_enabled",label:"Aceitar inscrições",type:"checkbox"},status]},
  parceiros:{title:"Parceiros e convênios",singular:"parceiro",table:"organizations",filter:{column:"kind",value:"partner"},fields:[{name:"name",label:"Nome",required:true},{name:"slug",label:"Endereço",required:true},{name:"logo_url",label:"Logo",type:"url"},{name:"contact_name",label:"Contato"},{name:"email",label:"E-mail",type:"email"},{name:"phone",label:"Telefone"},{name:"whatsapp",label:"WhatsApp"},{name:"website_url",label:"Site",type:"url"},{name:"presentation",label:"Apresentação",type:"textarea"},{name:"display_order",label:"Ordem",type:"number"},status]},
  associados:{title:"Associados",singular:"associado",table:"organizations",filter:{column:"kind",value:"associate"},fields:[{name:"name",label:"Nome",required:true},{name:"slug",label:"Endereço",required:true},{name:"segment",label:"Segmento"},{name:"logo_url",label:"Logo",type:"url"},{name:"email",label:"E-mail",type:"email"},{name:"phone",label:"Telefone"},{name:"whatsapp",label:"WhatsApp"},{name:"website_url",label:"Site",type:"url"},{name:"presentation",label:"Apresentação",type:"textarea"},{name:"display_order",label:"Ordem",type:"number"},status]},
  legislacao:{title:"Legislação e documentos",singular:"documento",table:"documents",fields:[{name:"title",label:"Título",required:true},{name:"slug",label:"Endereço",required:true},{name:"description",label:"Descrição",type:"textarea"},{name:"file_url",label:"Arquivo",type:"file",required:true},{name:"file_name",label:"Nome do arquivo"},{name:"category",label:"Categoria"},{name:"published_at",label:"Data de publicação",type:"datetime-local"},status]},
  vagas:{title:"Vagas",singular:"vaga",table:"jobs",fields:[{name:"title",label:"Cargo",required:true},{name:"slug",label:"Endereço",required:true},{name:"company",label:"Empresa"},{name:"location",label:"Local"},{name:"work_mode",label:"Modelo de trabalho"},{name:"employment_type",label:"Tipo de contratação"},{name:"description",label:"Descrição",type:"json"},{name:"application_url",label:"Link para candidatura",type:"url"},{name:"application_email",label:"E-mail para candidatura",type:"email"},{name:"expires_at",label:"Expira em",type:"datetime-local"},status]},
  configuracoes:{title:"Conteúdos e configurações",singular:"configuração",table:"site_settings",fields:[{name:"key",label:"Chave",required:true},{name:"label",label:"Nome"},{name:"group_name",label:"Área",required:true},{name:"value",label:"Conteúdo",type:"json",required:true}]},
  inscricoes:{title:"Inscrições recebidas",singular:"inscrição",table:"event_registrations",readOnly:true,fields:[]},
  formularios:{title:"Formulários recebidos",singular:"formulário",table:"form_submissions",readOnly:true,fields:[]},
};

export const adminNav=["banners","paginas","noticias","videos","agenda","parceiros","associados","legislacao","vagas","configuracoes","inscricoes","formularios"];
