import {NextRequest,NextResponse} from "next/server";
import {getAdminUser} from "@/lib/admin-auth";
import {resources} from "@/lib/cms";
import {database} from "@/lib/db";

async function allowed(){return Boolean(await getAdminUser())}
function normalize(value:unknown){if(value==="")return null;return value}
export async function POST(request:NextRequest,{params}:{params:Promise<{resource:string}>}){if(!await allowed())return NextResponse.json({error:"Não autorizado"},{status:401});const{resource:key}=await params;const resource=resources[key];if(!resource||resource.readOnly)return NextResponse.json({error:"Cadastro inválido"},{status:400});const body=await request.json();const fields=resource.fields.map(f=>f.name).filter(name=>body[name]!==undefined);if(resource.filter)fields.push(resource.filter.column);const values=fields.map(name=>name===resource.filter?.column?resource.filter.value:normalize(body[name]));const placeholders=values.map((_,i)=>`$${i+1}`).join(",");try{const rows=await database().query(`INSERT INTO ${resource.table} (${fields.join(",")}) VALUES (${placeholders}) RETURNING *`,values);return NextResponse.json(rows[0])}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Erro ao salvar"},{status:400})}}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{resource:string}>}){if(!await allowed())return NextResponse.json({error:"Não autorizado"},{status:401});const{resource:key}=await params;const resource=resources[key];if(!resource||resource.readOnly)return NextResponse.json({error:"Cadastro inválido"},{status:400});const body=await request.json();const fields=resource.fields.map(f=>f.name).filter(name=>body[name]!==undefined);if(!body.id||!fields.length)return NextResponse.json({error:"Dados incompletos"},{status:400});const values=fields.map(name=>normalize(body[name]));const sets=fields.map((name,i)=>`${name}=$${i+1}`).join(",");const rows=await database().query(`UPDATE ${resource.table} SET ${sets}, updated_at=now() WHERE id=$${values.length+1} RETURNING *`,[...values,body.id]);return NextResponse.json(rows[0])}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{resource:string}>}){if(!await allowed())return NextResponse.json({error:"Não autorizado"},{status:401});const{resource:key}=await params;const resource=resources[key];if(!resource)return NextResponse.json({error:"Cadastro inválido"},{status:400});const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"ID obrigatório"},{status:400});await database().query(`DELETE FROM ${resource.table} WHERE id=$1`,[id]);return NextResponse.json({ok:true})}
