import {NextRequest,NextResponse} from "next/server";
import {getAdminUser} from "@/lib/admin-auth";
import {resources} from "@/lib/cms";
import {database} from "@/lib/db";

async function allowed(){return Boolean(await getAdminUser())}
function normalize(value:unknown){if(value==="")return null;return value}
function slug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function flatten(row:Record<string,unknown>){return {...row,...(row.value&&typeof row.value==="object"&&!Array.isArray(row.value)?row.value:{})}}
function flattenVirtual(row:Record<string,unknown>,resource:(typeof resources)[string]){const result={...row};for(const[virtual,mapping]of Object.entries(resource.jsonVirtualFields||{})){const source=result[mapping.column];result[virtual]=source&&typeof source==="object"&&!Array.isArray(source)?(source as Record<string,unknown>)[mapping.property]:undefined}return result}
function mergeVirtualFields(resource:(typeof resources)[string],input:Record<string,unknown>){const body={...input};for(const[virtual,mapping]of Object.entries(resource.jsonVirtualFields||{})){if(body[virtual]===undefined)continue;const current=body[mapping.column];body[mapping.column]={...(current&&typeof current==="object"&&!Array.isArray(current)?current:{}),[mapping.property]:body[virtual]};delete body[virtual]}return body}
export async function POST(request:NextRequest,{params}:{params:Promise<{resource:string}>}){if(!await allowed())return NextResponse.json({error:"Não autorizado"},{status:401});const{resource:key}=await params;const resource=resources[key];if(!resource||resource.readOnly||resource.allowCreate===false)return NextResponse.json({error:"Cadastro inválido"},{status:400});const body=mergeVirtualFields(resource,await request.json());try{if(resource.settingsObject){const content=Object.fromEntries(resource.fields.filter(field=>body[field.name]!==undefined).map(field=>[field.name,normalize(body[field.name])]));const source=String(body[resource.autoKeyFrom||"title"]||"item");const settingKey=`${resource.settingsGroup||"settings"}.${slug(source)}-${Date.now().toString(36)}`;const label=String(body.title||source);const rows=await database().query("INSERT INTO site_settings (key,label,group_name,value) VALUES ($1,$2,$3,$4) RETURNING *",[settingKey,label,resource.settingsGroup||"general",JSON.stringify(content)]);return NextResponse.json(flatten(rows[0] as Record<string,unknown>))}const fields=resource.fields.map(f=>f.name).filter(name=>!resource.jsonVirtualFields?.[name]&&body[name]!==undefined);if(resource.filter)fields.push(resource.filter.column);const values=fields.map(name=>name===resource.filter?.column?resource.filter.value:normalize(body[name]));const placeholders=values.map((_,i)=>`$${i+1}`).join(",");const rows=await database().query(`INSERT INTO ${resource.table} (${fields.join(",")}) VALUES (${placeholders}) RETURNING *`,values);return NextResponse.json(flattenVirtual(rows[0] as Record<string,unknown>,resource))}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Erro ao salvar"},{status:400})}}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{resource:string}>}){if(!await allowed())return NextResponse.json({error:"Não autorizado"},{status:401});const{resource:key}=await params;const resource=resources[key];if(!resource||resource.readOnly)return NextResponse.json({error:"Cadastro inválido"},{status:400});const body=mergeVirtualFields(resource,await request.json());const primaryKey=resource.primaryKey||"id";const id=body[primaryKey];const fields=resource.fields.map(f=>f.name).filter(name=>!resource.jsonVirtualFields?.[name]&&body[name]!==undefined);if(!id||!fields.length)return NextResponse.json({error:"Dados incompletos"},{status:400});if(resource.settingsObject){const content=Object.fromEntries(fields.map(name=>[name,normalize(body[name])]));const label=body.title?String(body.title):null;const rows=await database().query("UPDATE site_settings SET value=value || $1::jsonb, label=COALESCE($2,label), updated_at=now() WHERE key=$3 RETURNING *",[JSON.stringify(content),label,id]);return NextResponse.json(flatten(rows[0] as Record<string,unknown>))}const values=fields.map(name=>normalize(body[name]));const sets=fields.map((name,i)=>resource.jsonMergeColumns?.includes(name)?`${name}=COALESCE(${name},'{}'::jsonb) || $${i+1}::jsonb`:`${name}=$${i+1}`).join(",");const rows=await database().query(`UPDATE ${resource.table} SET ${sets}, updated_at=now() WHERE ${primaryKey}=$${values.length+1} RETURNING *`,[...values,id]);return NextResponse.json(flattenVirtual(rows[0] as Record<string,unknown>,resource))}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{resource:string}>}){if(!await allowed())return NextResponse.json({error:"Não autorizado"},{status:401});const{resource:key}=await params;const resource=resources[key];if(!resource||resource.deletable===false)return NextResponse.json({error:"Cadastro inválido"},{status:400});const id=request.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"ID obrigatório"},{status:400});await database().query(`DELETE FROM ${resource.table} WHERE ${resource.primaryKey||"id"}=$1`,[id]);return NextResponse.json({ok:true})}
