import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowRight,BriefcaseBusiness,CalendarDays,EmptyState,Footer,Handshake,Header,Landmark,PageHero,services,Users} from "../site-components";
import {ContactForm,EventRegistration,MembershipForm} from "../public-forms";
import {safeQuery} from "@/lib/db";
type News={id:string;slug:string;title:string;excerpt:string|null;published_at:string;cover_image_url:string|null;content:unknown};
type Video={id:string;title:string;excerpt:string|null;video_url:string;cover_image_url:string|null};
type Job={id:string;title:string;company:string|null;location:string|null;employment_type:string|null;application_url:string|null};
type Event={id:string;kind:string;title:string;excerpt:string|null;starts_at:string;venue:string|null;registration_enabled:boolean};
type Organization={id:string;kind:string;name:string;segment:string|null;logo_url:string|null;website_url:string|null;presentation:string|null};
type Document={id:string;title:string;description:string|null;file_url:string;category:string|null};
const pages:Record<string,{eyebrow:string;title:string;text:string}>={
  sobre:{eyebrow:"Institucional",title:"Conheça a ACI Sindilojas",text:"Duas entidades, uma mesma força para representar e desenvolver quem empreende."},
  solucoes:{eyebrow:"Benefícios e serviços",title:"Soluções para o seu negócio",text:"Estrutura, orientação e vantagens que facilitam a rotina e impulsionam resultados."},
  noticias:{eyebrow:"Atualidades",title:"Notícias",text:"Acompanhe as ações, projetos e movimentos que fortalecem a comunidade empresarial."},
  "videos-lives":{eyebrow:"Conteúdo",title:"Vídeos e lives",text:"Informação, conversas e conhecimento para apoiar as decisões de quem empreende."},
  contato:{eyebrow:"Fale conosco",title:"Como podemos ajudar?",text:"Nossa equipe está pronta para orientar você e encontrar o canal certo para cada necessidade."},
  vagas:{eyebrow:"Oportunidades",title:"Vagas de trabalho",text:"Conectamos empresas da região a profissionais em busca de novas oportunidades."},
  "cursos-e-eventos":{eyebrow:"Agenda",title:"Cursos e eventos",text:"Conhecimento e conexões para transformar desafios em oportunidades."},
  convenios:{eyebrow:"Rede de benefícios",title:"Parceiros e convênios",text:"Condições e vantagens construídas para gerar valor aos associados."},
  associados:{eyebrow:"Nossa rede",title:"Empresas associadas",text:"Negócios que acreditam na força da colaboração e no desenvolvimento regional."},
  legislacao:{eyebrow:"Informação empresarial",title:"Legislação",text:"Conteúdos de apoio para acompanhar temas relevantes ao comércio e à indústria."},
  associe:{eyebrow:"Faça parte",title:"Cresça com uma rede ao seu lado",text:"Associe-se e tenha acesso a representação, conexões, serviços e oportunidades."},
  "politica-de-privacidade":{eyebrow:"Transparência",title:"Política de privacidade",text:"Informações sobre o tratamento de dados nos canais da entidade."},
  "termos-de-uso":{eyebrow:"Transparência",title:"Termos de uso",text:"Condições para utilização dos conteúdos e serviços digitais da entidade."},
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}

async function PageBody({slug}:{slug:string}){
  if(slug==="sobre")return <section className="section"><div className="container prose-grid"><div><span className="eyebrow">Nossa história</span><h2>Representatividade que atravessa gerações.</h2></div><div className="prose"><p>A Associação Comercial e Industrial de Três de Maio foi fundada em 27 de novembro de 1979. O Sindilojas foi fundado em 4 de novembro de 2002.</p><p>As duas entidades trabalham em conjunto, compartilhando ações e objetivos para assegurar melhores condições ao desenvolvimento das empresas representadas.</p></div><article className="value-card"><strong>Missão</strong><p>Assegurar que as empresas da base representada tenham as melhores condições para se desenvolver, melhorando a qualidade de vida da sociedade.</p></article><article className="value-card"><strong>Visão</strong><p>Ser a opção mais eficaz para a melhoria contínua da representatividade da base representada.</p></article></div><div className="container leadership"><h2>Governança</h2><div><article><span>ACI</span><h3>Jesildo Moura de Lima</h3><p>Presidente</p></article><article><span>Sindilojas</span><h3>Dilson José Mireski</h3><p>Presidente</p></article></div></div></section>;
  if(slug==="solucoes")return <section className="section"><div className="container service-grid light-grid">{services.map(({title,description,icon:Icon})=><article className="service-card" key={title}><Icon size={28}/><h3>{title}</h3><p>{description}</p><a href="https://wa.me/5555999954200">Solicitar informações <ArrowRight size={17}/></a></article>)}</div></section>;
  if(slug==="noticias"){const list=await safeQuery<News>("SELECT id,slug,title,excerpt,published_at,cover_image_url,content FROM posts WHERE kind='news' AND status='published' ORDER BY published_at DESC NULLS LAST").catch(()=>[]);return <section className="section"><div className="container editorial-list">{list.map((item,i)=><article key={item.slug}><time>{new Date(item.published_at).toLocaleDateString("pt-BR")}</time><span>0{i+1}</span><h2>{item.title}</h2><Link href={`/noticias/${item.slug}`}>Ler notícia <ArrowRight size={16}/></Link></article>)}</div></section>}
  if(slug==="videos-lives"){const items=await safeQuery<Video>("SELECT id,title,excerpt,video_url,cover_image_url FROM posts WHERE kind='video' AND status='published' ORDER BY published_at DESC NULLS LAST").catch(()=>[]);return <section className="section"><div className="container video-grid">{items.map(item=><article key={item.id}><img src={item.cover_image_url||"/brand/institucional.webp"} alt=""/><div><span className="eyebrow">Vídeo</span><h2>{item.title}</h2><p>{item.excerpt}</p><a className="button button-blue" href={item.video_url} target="_blank" rel="noreferrer">Assistir no YouTube <ArrowRight size={17}/></a></div></article>)}</div></section>}
  if(slug==="contato")return <section className="section"><div className="container contact-grid"><div className="contact-list">{[["Atendimento","(55) 9 9995-4200\n(55) 3535-1338"],["Financeiro","(55) 9 9619-3291"],["Marketing","(55) 9 9696-6404"],["Telefonia","(55) 9 9622-1885"],["Comercial e eventos","(55) 9 9935-8073"]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div><ContactForm/></div></section>;
  if(slug==="vagas"){const items=await safeQuery<Job>("SELECT id,title,company,location,employment_type,application_url FROM jobs WHERE status='published' AND (expires_at IS NULL OR expires_at>=now()) ORDER BY published_at DESC NULLS LAST").catch(()=>[]);return <section className="section"><div className="container"><div className="demo-note">Conteúdos demonstrativos para visualização do layout.</div><div className="public-card-grid">{items.map(item=><article key={item.id}><span className="eyebrow">{item.company||"Oportunidade"}</span><h2>{item.title}</h2><p>{[item.location,item.employment_type].filter(Boolean).join(" · ")}</p>{item.application_url&&<a className="text-link" href={item.application_url}>Candidatar-se <ArrowRight size={16}/></a>}</article>)}</div></div></section>}
  if(slug==="cursos-e-eventos"){const items=await safeQuery<Event>("SELECT id,kind,title,excerpt,starts_at,venue,registration_enabled FROM events WHERE status='published' AND starts_at>=now() ORDER BY starts_at").catch(()=>[]);return <section className="section"><div className="container"><div className="filter-labels"><span>Eventos</span><span>Cursos</span><span>Calendário</span></div><div className="calendar-list">{items.map(item=><article key={item.id}><time><strong>{new Date(item.starts_at).toLocaleDateString("pt-BR",{day:"2-digit"})}</strong>{new Date(item.starts_at).toLocaleDateString("pt-BR",{month:"short",year:"numeric"})}</time><div><span>{item.kind==="course"?"Curso":"Evento"}</span><h2>{item.title}</h2><p>{item.excerpt} {item.venue&&`· ${item.venue}`}</p></div>{item.registration_enabled&&<details><summary className="button button-blue">Inscreva-se</summary><EventRegistration eventId={item.id} title={item.title}/></details>}</article>)}</div></div></section>}
  if(slug==="convenios"||slug==="associados"){const kind=slug==="convenios"?"partner":"associate";const items=await safeQuery<Organization>("SELECT id,kind,name,segment,logo_url,website_url,presentation FROM organizations WHERE kind=$1 AND status='published' ORDER BY display_order,name",[kind]).catch(()=>[]);return <section className="section"><div className="container"><div className="demo-note">Nomes e informações demonstrativos para composição do site.</div><div className="organization-grid">{items.map(item=><article key={item.id}>{item.logo_url&&<img src={item.logo_url} alt={`Logo ${item.name}`}/>}<span>{item.segment}</span><h2>{item.name}</h2><p>{item.presentation}</p>{item.website_url&&<a className="text-link" href={item.website_url}>Visitar site <ArrowRight size={16}/></a>}</article>)}</div></div></section>}
  if(slug==="legislacao"){const items=await safeQuery<Document>("SELECT id,title,description,file_url,category FROM documents WHERE status='published' ORDER BY published_at DESC NULLS LAST").catch(()=>[]);return <section className="section"><div className="container"><div className="demo-note">Documentos demonstrativos para visualização do cadastro.</div><div className="document-list">{items.map(item=><a href={item.file_url} key={item.id}><Landmark/><div><span>{item.category||"Documento"}</span><h2>{item.title}</h2><p>{item.description}</p></div><strong>Acessar</strong></a>)}</div></div></section>}
  if(slug==="associe")return <section className="section"><div className="container join-grid"><div><span className="eyebrow">Por que se associar</span><h2>Mais voz, mais conexões, mais possibilidades.</h2><ul><li>Representatividade empresarial</li><li>Acesso a soluções e serviços</li><li>Condições em parceiros e convênios</li><li>Cursos, eventos e networking</li></ul></div><div className="join-card membership-card"><span>Seja um associado</span><h3>Conte um pouco sobre o seu negócio.</h3><MembershipForm/></div></div></section>;
  return <section className="section"><div className="container prose"><p>O conteúdo completo desta página será publicado pela ACI Sindilojas.</p></div></section>;
}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const fallback=pages[slug];if(!fallback)notFound();const managed=(await safeQuery<{eyebrow:string;title:string;summary:string}>("SELECT eyebrow,title,summary FROM pages WHERE slug=$1 AND status='published' LIMIT 1",[slug]).catch(()=>[]))[0];const page=managed?{eyebrow:managed.eyebrow||fallback.eyebrow,title:managed.title||fallback.title,text:managed.summary||fallback.text}:fallback;return <><Header/><main><PageHero {...page}/><PageBody slug={slug}/></main><Footer/></>}
