import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,CalendarDays} from "lucide-react";
import {Footer,Header} from "@/app/site-components";
import {safeQuery} from "@/lib/db";

type NewsItem={id:string;slug:string;title:string;excerpt:string|null;published_at:string;cover_image_url:string|null;content:{body?:string[];note?:string;gallery?:string[]}|string};
async function getNews(slug:string){return (await safeQuery<NewsItem>("SELECT id,slug,title,excerpt,published_at,cover_image_url,content FROM posts WHERE kind='news' AND status='published' AND slug=$1 LIMIT 1",[slug]).catch(()=>[]))[0]}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const item=await getNews(slug);return item?{title:`${item.title} | ACI Sindilojas`,description:item.excerpt}:{title:"Notícia não encontrada | ACI Sindilojas"}}

export default async function NewsPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const item=await getNews(slug);if(!item)notFound();const content=typeof item.content==="string"?JSON.parse(item.content):item.content;const paragraphs=Array.isArray(content?.body)&&content.body.length?content.body:item.excerpt?[item.excerpt]:[];const gallery:string[]=Array.isArray(content?.gallery)?content.gallery.filter((image:unknown):image is string=>typeof image==="string"&&image.length>0):[];return <><Header/><main><article className="news-detail"><header><div className="container"><Link href="/noticias" className="news-back"><ArrowLeft size={16}/> Voltar para notícias</Link><span className="eyebrow light">Notícias</span><h1>{item.title}</h1><p>{item.excerpt}</p><time><CalendarDays size={16}/>{new Date(item.published_at).toLocaleDateString("pt-BR",{day:"2-digit",month:"long",year:"numeric"})}</time></div></header><div className="container news-detail-body">{item.cover_image_url&&<img src={item.cover_image_url} alt={`Imagem de capa — ${item.title}`}/>}<div className="prose">{paragraphs.map((paragraph:string,index:number)=><p key={`${index}-${paragraph}`}>{paragraph}</p>)}{content?.note&&<aside>{content.note}</aside>}</div></div>{gallery.length>0&&<section className="container news-gallery" aria-labelledby="news-gallery-title"><div className="news-gallery-heading"><span className="eyebrow">Galeria</span><h2 id="news-gallery-title">Fotos da notícia</h2></div><div>{gallery.map((image,index)=><img key={`${image}-${index}`} src={image} alt={`${item.title} — foto ${index+1}`}/>)}</div></section>}</article></main><Footer/></>}
